/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umzug;

/**
 *
 * @author rajninal
 */
public class UmzugJPanel extends javax.swing.JPanel
{
    /**
     * Creates new form UmzugJPanel
     */
    String tabName = "";
    
    public UmzugJPanel()
    {
        super();
        initComponents();
    }
    
    @Override
    public String getName() 
    {
        tabName = jPanel_Umzug.getName();
        return tabName;
    }
    
//    public void panelLoad() 
//    {
//        
//    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_Umzug = new javax.swing.JPanel();
        jComboBox_Kategorie = new javax.swing.JComboBox();
        jLabel_Kategorie = new javax.swing.JLabel();
        jLabel_Dringlichkeit = new javax.swing.JLabel();
        jComboBox_Dringlichkeit = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane_Artikeln = new javax.swing.JScrollPane();
        jTbl_Artikeln = new javax.swing.JTable();

        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel_Umzug.setName("jPanel_Umzug"); // NOI18N
        jPanel_Umzug.setLayout(new java.awt.GridBagLayout());

        jComboBox_Kategorie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Kategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Flür", "Schlafzimmer", "Küche", "Wohnzimmer", "Bad" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel_Umzug.add(jComboBox_Kategorie, gridBagConstraints);

        jLabel_Kategorie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Kategorie.setText("Kategorie:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel_Umzug.add(jLabel_Kategorie, gridBagConstraints);

        jLabel_Dringlichkeit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Dringlichkeit.setText("Dringlichkeit:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel_Umzug.add(jLabel_Dringlichkeit, gridBagConstraints);

        jComboBox_Dringlichkeit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Dringlichkeit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Dringend", "Nicht dringend", "Irgendwann" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel_Umzug.add(jComboBox_Dringlichkeit, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Umzug to Do Liste");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_Umzug.add(jLabel3, gridBagConstraints);

        jTbl_Artikeln.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_Artikeln.setViewportView(jTbl_Artikeln);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel_Umzug.add(jScrollPane_Artikeln, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel_Umzug, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_Dringlichkeit;
    private javax.swing.JComboBox jComboBox_Kategorie;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Dringlichkeit;
    private javax.swing.JLabel jLabel_Kategorie;
    private javax.swing.JPanel jPanel_Umzug;
    private javax.swing.JScrollPane jScrollPane_Artikeln;
    private javax.swing.JTable jTbl_Artikeln;
    // End of variables declaration//GEN-END:variables
}
