/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umzug;

import java.awt.*;

/**
 *
 * @author rajninal
 */
public class UmzugFrame extends javax.swing.JFrame
{
    /**
     * Creates new form UmzugFrame
     */    
    UmzugJPanel jpUmzugPane = null;
    public String tabName = "";
    public CardLayout cardLayout = null;
    
    public UmzugFrame()
    {
        super();
        initComponents();        
        umzugPanelInit();
        
        cardLayout = (CardLayout) jpCardPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_Menü = new javax.swing.JPanel();
        jLabel_Menü = new javax.swing.JLabel();
        jToolBar_Menü = new javax.swing.JToolBar();
        jButton_Neu = new javax.swing.JButton();
        jLabel1_12 = new javax.swing.JLabel();
        jButton_Speichern = new javax.swing.JButton();
        jLabel1_14 = new javax.swing.JLabel();
        jButton_Löschen = new javax.swing.JButton();
        jLabel1_13 = new javax.swing.JLabel();
        jPanel_Daten = new javax.swing.JPanel();
        jpCardPanel = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Umzug Tool");
        setIconImages(null);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel_Menü.setBackground(new java.awt.Color(58, 110, 165));
        jPanel_Menü.setName("jPanel_Menü"); // NOI18N
        jPanel_Menü.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel_Menü.setLayout(new java.awt.GridBagLayout());

        jLabel_Menü.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Menü.setText("Menü");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel_Menü.add(jLabel_Menü, gridBagConstraints);

        jToolBar_Menü.setBackground(new java.awt.Color(58, 110, 165));
        jToolBar_Menü.setBorder(null);
        jToolBar_Menü.setName("jToolBar_Menü"); // NOI18N

        jButton_Neu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umzug/icons/32-document-new.png"))); // NOI18N
        jButton_Neu.setFocusable(false);
        jButton_Neu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Neu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Menü.add(jButton_Neu);

        jLabel1_12.setMaximumSize(new java.awt.Dimension(10, 43));
        jLabel1_12.setMinimumSize(new java.awt.Dimension(10, 43));
        jLabel1_12.setPreferredSize(new java.awt.Dimension(10, 43));
        jToolBar_Menü.add(jLabel1_12);

        jButton_Speichern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umzug/icons/32-media-floppy.png"))); // NOI18N
        jButton_Speichern.setFocusable(false);
        jButton_Speichern.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Speichern.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Menü.add(jButton_Speichern);

        jLabel1_14.setMaximumSize(new java.awt.Dimension(10, 43));
        jLabel1_14.setMinimumSize(new java.awt.Dimension(10, 43));
        jLabel1_14.setPreferredSize(new java.awt.Dimension(10, 43));
        jToolBar_Menü.add(jLabel1_14);

        jButton_Löschen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umzug/icons/32-delete.png"))); // NOI18N
        jButton_Löschen.setFocusable(false);
        jButton_Löschen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Löschen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar_Menü.add(jButton_Löschen);

        jLabel1_13.setMaximumSize(new java.awt.Dimension(10, 43));
        jLabel1_13.setMinimumSize(new java.awt.Dimension(10, 43));
        jLabel1_13.setPreferredSize(new java.awt.Dimension(10, 43));
        jToolBar_Menü.add(jLabel1_13);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        jPanel_Menü.add(jToolBar_Menü, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(jPanel_Menü, gridBagConstraints);

        jPanel_Daten.setName("jPanel_Daten"); // NOI18N
        jPanel_Daten.setLayout(new java.awt.GridBagLayout());

        jpCardPanel.setName("jpCardPanel"); // NOI18N
        jpCardPanel.setLayout(new java.awt.CardLayout());

        jpMenu.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createEtchedBorder()));
        jpMenu.setMinimumSize(new java.awt.Dimension(500, 500));
        jpMenu.setName("jpMenu"); // NOI18N
        jpMenu.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jpCardPanel.add(jpMenu, "jpMenu");
        jpMenu.getAccessibleContext().setAccessibleName("jpMenu");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel_Daten.add(jpCardPanel, gridBagConstraints);
        jpCardPanel.getAccessibleContext().setAccessibleName("jpCardPanel");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel_Daten, gridBagConstraints);
        jPanel_Daten.getAccessibleContext().setAccessibleName("jPanel_Daten");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void showFirstPanel()
    {
//        jpUmzugPane.panelLoad();
        Umzug.mainFrame.tabName = "jPanel_Umzug";
        cardLayout.show(jpCardPanel, tabName);    
    }
    
    private void umzugPanelInit() 
    {
        jpUmzugPane = new UmzugJPanel();

        tabName = jpUmzugPane.getName();
        jpCardPanel.add(jpUmzugPane, tabName);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Löschen;
    private javax.swing.JButton jButton_Neu;
    private javax.swing.JButton jButton_Speichern;
    private javax.swing.JLabel jLabel1_12;
    private javax.swing.JLabel jLabel1_13;
    private javax.swing.JLabel jLabel1_14;
    private javax.swing.JLabel jLabel_Menü;
    private javax.swing.JPanel jPanel_Daten;
    private javax.swing.JPanel jPanel_Menü;
    private javax.swing.JToolBar jToolBar_Menü;
    private javax.swing.JPanel jpCardPanel;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
